language: node_js

node_js: "9"

script:
  - npm run package
  - npm run make

branches:
  only:
    - master

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change
